# -*- coding: utf-8 -*-
{
    'name': 'GDPR Platform',
    'version': '19.0.1.0.0',
    'category': 'Privacy',
    'summary': 'Complete GDPR compliance platform – global block, unsubscribe, audit log, dashboard',
    'author': 'Vidir',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'contacts',
        'crm',
        'sale_management',
        'account',
        'mass_mailing',
        'marketing_automation',
        'sms',
        'social',
        'helpdesk',
        'website',
        'portal',
        'sale_subscription',
        'base_automation',
    ],
    'data': [
        'security/gdpr_security.xml',
        'security/ir.model.access.csv',
        'data/gdpr_mail_templates.xml',
        'data/gdpr_automated_actions.xml',
        'data/gdpr_server_actions.xml',
        'views/gdpr_log_views.xml',
        'views/gdpr_dashboard_views.xml',
        'views/res_partner_views.xml',
        'views/crm_lead_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/gdpr_partner_actions.xml',
        'views/gdpr_menu.xml',
        'views/gdpr_website_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'gdpr_platform/static/src/css/gdpr_platform.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
